chore: refactored senior manager access as a subclass
ADORSYS-GIS/ledgers pull request #24
Opened 2024-09-30 09:22 UTC by Koufan-De-King

Created 
- seniormanageraccess class, 
- a repository for it's eventual connection to the database 

and wrote a basic test using JUnit.

2024-09-30 09:50 UTC, NkwaTambe requested changes

2024-09-30 09:50 UTC, NkwaTambe commented on ledgers-bank-account-access-management/ledgers-bank-account-access-repository/src/main/java/de/adorsys/ledgers/baam/db/domain/BankAccountAccess.java
> +    public AccessStatus status; // Active, restricted, or suspended
Hello @Koufan-De-King  Please make these field **private**... 
Declaring fields as private hides the implementation details and allows you to control how these fields are accessed or modified.
When fields are private, you can provide getter and setter methods to control access, which is the correct way to expose object data.

2024-09-30 10:12 UTC, NkwaTambe commented on ledgers-bank-account-access-management/ledgers-bank-account-access-repository/src/test/java/de/adorsys/ledgers/baam/db/domain/SeniorManagerAccessTest.java
> +}
Good job @Koufan-De-King 
 I would like to suggest some enhancements to incorporate H2 database usage and dependency injection for our tests.

**Dependency Injection:** We will use Spring's **@Autowired annotation** to inject the SeniorManagerAccessRepository, allowing us to persist test data into the H2 database.

and also from the  **ledgers** project structure, i think these test file should be in the test repository package

**Example implementation**
```public class SeniorManagerAccessTest {

    @Autowired
    private SeniorManagerAccessRepository seniorManagerAccessRepository;

    @Test
    public void testCreateManagerRole() {
        SeniorManagerAccess seniorManager = new SeniorManagerAccess();
        seniorManager.createManagerRole("Manager1", "CAN_VIEW");

        // Persist to the H2 database
        seniorManagerAccessRepository.save(seniorManager);

        assertTrue(seniorManager.getManagerRoles().containsKey("Manager1"));
        assertEquals("CAN_VIEW", seniorManager.getManagerRoles().get("Manager1"));
    }```

2024-09-30 17:28 UTC, yvanhenang approved these changes

2024-10-01 06:35 UTC, NkwaTambe approved these changes

2024-10-01 06:38 UTC, merged