Implement ledgers deposit rest api
ADORSYS-GIS/ledgers pull request #29
Opened 2024-10-01 14:28 UTC by Elwizzy12

Implement the ledgers-deposit-account-rest-api module and have added REST API endpoints for:
Creating a bank account.
Adding money to the account.
Querying account balances.
Transferring money between accounts.
Ensure no access control is implemented for now.

2024-10-02 21:19 UTC, NkwaTambe commented on ledgers-deposit-account/ledgers-deposit-account-service-api/pom.xml
> +        </dependency>
do you need these dependency in the `ledgers-deposit-account module` ??

2024-10-03 06:39 UTC, Arielpetit requested changes

2024-10-03 06:39 UTC, Arielpetit commented on ledgers-deposit-account/ledgers-deposit-account-service-api/src/main/java/de/adorsys/ledgers/deposit/api/domain/payment/PaymentTO.java
> +import de.adorsys.ledgers.middleware.api.domain.payment.TransactionStatusTO;
Hello @Elwizzy12  i don"t think this import must come from the middle ware please fix this

2024-10-03 06:39 UTC, Arielpetit commented on ledgers-deposit-account/ledgers-deposit-account-service-api/src/main/java/de/adorsys/ledgers/deposit/api/domain/payment/PaymentTargetTO.java
> +import de.adorsys.ledgers.middleware.api.domain.payment.RemittanceInformationStructuredTO;
Same here, please review this

2024-10-03 06:39 UTC, Arielpetit commented on ledgers-deposit-account/ledgers-deposit-account-service-api/src/main/java/de/adorsys/ledgers/deposit/api/domain/sca/SCAResponseTO.java
> +import de.adorsys.ledgers.middleware.api.domain.um.ScaUserDataTO;
Do same for here please

2024-10-03 06:40 UTC, Elwizzy12 commented on ledgers-deposit-account/ledgers-deposit-account-service-api/pom.xml
> +        </dependency>
@Elwizzy12 Thanks for pointing this out.

2024-10-04 14:06 UTC, Koufan-De-King submitted a review, later dismissed

2024-10-07 08:07 UTC, Arielpetit approved these changes, later dismissed
Looks good

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +    }
Missing default case. This might lead to unforeseen behavior if new error code are added and not mapped.
```suggestion
    public static HttpStatus resolveHttpStatusByCode(DepositErrorCode code) {
        return container.getOrDefault(code, BAD_REQUEST) ;
    }
```

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +        container.put(INSUFFICIENT_FUNDS, BAD_REQUEST);
Insufficient fund is a business and not a technical condition

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +        container.put(DEPOSIT_ACCOUNT_EXISTS, BAD_REQUEST);
I guess this error is true at creation, can you please comment

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +        container.put(PAYMENT_PROCESSING_FAILURE, BAD_REQUEST);
You mean INTERNAL_ERROR or BAD_Request?

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +        container.put(PAYMENT_WITH_ID_EXISTS, BAD_REQUEST);
I guess this error is true at creation, can you please comment

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +    }
Please review all mapping by verifying what error codes are thrown such as to map to the corresponding http status code

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/ExceptionAdvisor.java
> +        log.error("INTERNAL SERVER ERROR", ex);
It is good that you have used the ```globalExceptionHandler ``` but you can also consider using a more specific exception hierarchy to provide more informative error responses. For example, you could have separate handlers for RuntimeException and CheckedException.

2024-10-07 14:02 UTC, nancymuyeh commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/ExceptionAdvisor.java
> +        log.error(ex.getDevMsg());
The devMessage is currently exposed in the response body. This might reveal sensitive information in production. Please consider evaluating if a separate logging mechanism for development environments is more appropriate.

2024-10-07 15:04 UTC, Elwizzy12 commented on ledgers-deposit-account/ledgers-deposit-account-rest-api/src/main/java/de/adorsys/ledgers/deposit/api/exception/DepositHttpStatusResolver.java
> +        container.put(PAYMENT_PROCESSING_FAILURE, BAD_REQUEST);
If the failure is related to a system or server-side issue, it should return INTERNAL_SERVER_ERROR (500). If it is due to invalid input from the client, it should return BAD_REQUEST (400).

2024-10-08 06:45 UTC, NkwaTambe submitted a review, later dismissed

2024-10-08 07:12 UTC, Koufan-De-King approved these changes

2024-10-08 07:13 UTC, Arielpetit approved these changes

2024-10-08 07:14 UTC, merged