chore: created and tested PoAAccess entity
ADORSYS-GIS/ledgers pull request #37
Opened 2024-10-02 13:18 UTC by Koufan-De-King

2024-10-02 21:50 UTC, NkwaTambe requested changes
Good job @Koufan-De-King 

please look through  your code again and ticket description..

you can reconsider refactoring your code if you want

2024-10-02 21:50 UTC, NkwaTambe commented on ledgers-bank-account-access-management/ledgers-bank-account-access-repository/src/main/java/de/adorsys/ledgers/baam/db/domain/PoAAccess.java
> +
Please use the `Getters and Setter annotation properly`

you have `lombok` already, make good use of it

you are doing a great job but your code can be done in a better way.

you can refer to these : https://medium.com/@wandercosta/lombok-getters-and-setters-10ce392188f6

2024-10-03 09:17 UTC, NkwaTambe commented
Please add ticket description

2024-10-03 09:19 UTC, Koufan-De-King commented
> Please add ticket description

Done

2024-10-04 11:24 UTC, NkwaTambe commented on ledgers-bank-account-access-management/ledgers-bank-account-access-repository/src/main/java/de/adorsys/ledgers/baam/db/repository/DelegatedAccessRepository.java
> +}
`accountId123`????


were is these from  ?

2024-10-04 11:35 UTC, NkwaTambe approved these changes

2024-10-04 11:37 UTC, Arielpetit approved these changes
Looks good

2024-10-04 14:12 UTC, merged